server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hikers?characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 1234
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

logging:
  level:
    wyl: debug

sys-setting:
  uploadPath: D:/hpics/
  topicLoadNum: 20
